apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: ghcr.io/drs-t0m0/cicd-handson-2021-code/go-image:11
        ports:
        - containerPort: 9090
      imagePullSecrets:
      - name: dockerconfigjson-github-com

